AVRO-3435: Add --version to avrogen tool
apache/avro pull request #1583
Opened 2022-03-07 15:31 UTC by zcsizmadia

Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO-3435
  - https://issues.apache.org/jira/browse/AVRO-3435
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

2022-03-08 19:45 UTC, martin-g approved these changes

2022-03-10 15:24 UTC, zcsizmadia commented
Unit tests should be added after #1595 is merged

2022-03-18 20:06 UTC, KyleSchoonover requested changes

2022-03-19 00:09 UTC, zcsizmadia commented on lang/csharp/src/apache/codegen/AvroGen.cs
> +            if (args.Contains("--version"))
Good catch. I added -V to the cpp avrogen and I intended to add for C# as well.

2022-03-20 14:38 UTC, zcsizmadia commented
@martin-g I added some addition unit tests to make sure that the version returned by avrogen and the version  for the main library match and both are SemVer2.0 compliant. Additionally added some tests to make sure that some mandatory attrributes are always defined (e.g. Company, Description ...)

2022-03-30 05:24 UTC, KyleSchoonover approved these changes

2022-03-30 06:16 UTC, merged