AVRO-3692: [rust] Make serde deserializer support serde flatten
apache/avro pull request #2024
Opened 2022-12-17 21:28 UTC by Ten0

## What is the purpose of the change

This PR fixes deserializing into rust structures that use `#[serde(flatten)]`, which is a very common use case when using `serde`.

## Verifying this change

This change added the corresponding test:
```bash
cargo test -- test_from_value_struct_flatten
```

## Documentation

This is a minor enough change that it probably doesn't need to be documented - users would hope for this to work from the beginning.

2022-12-18 12:09 UTC, martin-g requested changes

2022-12-18 12:09 UTC, martin-g commented on lang/rust/avro/src/de.rs
>              _ => Err(de::Error::custom("not a map")),
```suggestion
            _ => Err(de::Error::custom(format!("Expected a Record or a Map! Got: {:?}", &self.input))),
```

2022-12-18 12:09 UTC, martin-g commented on lang/rust/avro/src/de.rs
> +    fn test_from_value_struct_flatten() {
```suggestion
    fn test_avro_3692_from_value_struct_flatten() {
```

2022-12-18 14:28 UTC, Ten0 commented
Thanks for the quick review. :)
I've ~applied the suggested changes.

2022-12-18 19:24 UTC, martin-g approved these changes

2022-12-18 19:57 UTC, merged

2022-12-18 19:59 UTC, martin-g commented
Thank you, @Ten0 !

2022-12-28 23:58 UTC, Ten0 commented
What would be a timeline for a release of this and the other already-merged-not-released fixes?

2023-01-03 14:14 UTC, Ten0 commented
Thank you very much! 😊